defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - model: timelag

verbose: 100

data:
  # training set
  train_no_dev:
    in_dir:
    out_dir:

  # development set
  dev:
    in_dir:
    out_dir:

  # data loader
  num_workers: 2
  batch_size: 4
  pin_memory: true

optim:
  name: Adam
  params:
    lr: 0.001
    betas: [0.9, 0.999]

train:
  out_dir: exp
  nepochs: 50
  checkpoint_epoch_interval: 10

  masked_loss: true

resume:
  checkpoint:
  load_optimizer: false

cudnn:
  benchmark: false
  deterministic: false